In [1]:
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from neuralnetwork import NeuralNetwork

In [2]:
# Run only if you need to install nltk.corpus and nltk.stem
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
# Read the data set and parse independent lines
fd = open("Assignment_2_data.txt","r")
file_data = fd.read()
lines = (file_data).splitlines()

In [4]:
# Create Necessary objects
ps = PorterStemmer()
y_target_names = []
x = []
stop_words = set(stopwords.words('english'))
unique_tokens = set()

In [5]:
# Pasing input file into labels and features 
for i in range(len(lines)): 
    # Splitting based on white space and non alpha numberic characters
    words_tokens = re.split('\W+',lines[i])
    words_tokens = list(filter(lambda temp: (temp != '' ),words_tokens)) 
    
    # Removing stop word from the data
    filtered_sentence = []
    for w in words_tokens:
        if w not in stop_words:
        # Applying porter stemmer
            stemmed_word = ps.stem(w).lower()
            filtered_sentence.append(stemmed_word)


    # Store pre processed data in x and y_target_names
    y_target_names.append(filtered_sentence[0])
    x.append(filtered_sentence[1:])
    unique_tokens.update(filtered_sentence[1:])

In [6]:
# Declare variables for one hot encoding
N = len(x)
unique_tokens = list(unique_tokens)
encoding_length = (len(unique_tokens))
x_encoded = np.zeros( ( N , encoding_length) )


In [7]:
# Binary encoding of features and labels
for i in range(N):
    for j in x[i]:
        ind = unique_tokens.index(j)
        x_encoded[i][ind] = 1;
        
y_target = np.zeros((N,1))
for i in range(len(y_target_names)):
    if(y_target_names[i] == "ham"):
        y_target[i] = 1

In [8]:
# Split training and test error
trainN = int(0.8*N)

X_train = x_encoded[0:trainN]
y_train = y_target[0:trainN]

X_test = x_encoded[trainN:]
y_test = y_target[trainN:]

In [9]:
N,M = X_train.shape

In [9]:
nn = NeuralNetwork(M,np.array([100,50]),1)

In [ ]:
nn.train(X_train,y_train,X_test,y_test)

[[ 1.]
 [ 0.]
 [ 1.]
 ..., 
 [ 1.]
 [ 1.]
 [ 1.]]
-----------Ratio of Correct predictions over testset(384/1115)-----------
-----------Ratio of Correct predictions over training set(1446/4459)-----------
Epoch (1/500) Training Error : 0.849007
Epoch (2/500) Training Error : 0.672972
Epoch (3/500) Training Error : 0.585639
Epoch (4/500) Training Error : 0.538607
Epoch (5/500) Training Error : 0.510762
Epoch (6/500) Training Error : 0.492753
Epoch (7/500) Training Error : 0.480138
Epoch (8/500) Training Error : 0.470648
Epoch (9/500) Training Error : 0.463043
Epoch (10/500) Training Error : 0.456610
Epoch (11/500) Training Error : 0.450916
Epoch (12/500) Training Error : 0.445692
Epoch (13/500) Training Error : 0.440761
Epoch (14/500) Training Error : 0.436009
Epoch (15/500) Training Error : 0.431356
Epoch (16/500) Training Error : 0.426749
Epoch (17/500) Training Error : 0.422152
Epoch (18/500) Training Error : 0.417539
Epoch (19/500) Training Error : 0.412894
Epoch (20/500) Training Er

In [10]:
nn2 = NeuralNetwork(M,np.array([100,50]),2)

In [ ]:
nn2.train(X_train,y_train,X_test,y_test,method="two")

[[ 0.]
 [ 1.]
 [ 0.]
 ..., 
 [ 1.]
 [ 1.]
 [ 1.]]
-----------Ratio of Correct predictions over testset(795/1115)-----------
-----------Ratio of Correct predictions over training set(3288/4459)-----------
Epoch (1/500) Training Error : 0.236664
Epoch (2/500) Training Error : 0.237191
Epoch (3/500) Training Error : 0.237698
Epoch (4/500) Training Error : 0.238187
Epoch (5/500) Training Error : 0.238658
Epoch (6/500) Training Error : 0.239113
Epoch (7/500) Training Error : 0.239554
Epoch (8/500) Training Error : 0.239980
Epoch (9/500) Training Error : 0.240393
Epoch (10/500) Training Error : 0.240795
Epoch (11/500) Training Error : 0.241185
Epoch (12/500) Training Error : 0.241564
Epoch (13/500) Training Error : 0.241934
Epoch (14/500) Training Error : 0.242294
Epoch (15/500) Training Error : 0.242646
Epoch (16/500) Training Error : 0.242990
Epoch (17/500) Training Error : 0.243325
Epoch (18/500) Training Error : 0.243653
Epoch (19/500) Training Error : 0.243974
Epoch (20/500) Training Er

Epoch (180/500) Training Error : 0.249996
Epoch (181/500) Training Error : 0.250011
Epoch (182/500) Training Error : 0.250028
Epoch (183/500) Training Error : 0.250045
Epoch (184/500) Training Error : 0.250063
Epoch (185/500) Training Error : 0.250082
Epoch (186/500) Training Error : 0.250101
Epoch (187/500) Training Error : 0.250122
Epoch (188/500) Training Error : 0.250144
Epoch (189/500) Training Error : 0.250166
Epoch (190/500) Training Error : 0.250190
Epoch (191/500) Training Error : 0.250214
Epoch (192/500) Training Error : 0.250240
Epoch (193/500) Training Error : 0.250267
Epoch (194/500) Training Error : 0.250294
Epoch (195/500) Training Error : 0.250323
Epoch (196/500) Training Error : 0.250353
Epoch (197/500) Training Error : 0.250385
Epoch (198/500) Training Error : 0.250417
Epoch (199/500) Training Error : 0.250451
Epoch (200/500) Training Error : 0.250486
[[ 1.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 1.]
 [ 0.]]
-----------Ratio of Correct predictions over testset(646/1115)------